export const COLORS = {
  gray90: "hsl(0 0% 90%)",
  gray10: "hsl(0 0% 10%)",
  blue: "hsl(220 90% 50%)",
};

const rem = (px) => `${px / 16}rem`;

export const FONT_SIZES = {
  brandTitle: rem(16),
  brandSubtitle: rem(8),
  pageTitle: rem(14),
  navItem: rem(13),
  navSubItem: rem(12),
  input: rem(14),
  userName: rem(13),
  userRole: rem(11),
  menuItem: rem(14),

  dashboardMetricTitle: rem(12),
  dashboardMetricValue: rem(20),
  dashboardMetricUnit: rem(12),
  dashboardMetricMeta: rem(10),
  dashboardCardTitle: rem(12),
  dashboardPanelTitle: rem(12),
  dashboardPanelAction: rem(12),
  dashboardLegendLabel: rem(10),
  dashboardLegendValue: rem(10),
  dashboardLegendRatio: rem(10),
  dashboardDonutCenterLabel: rem(10),
  dashboardDonutCenterValue: rem(20),
  dashboardMapLabel: rem(10),
  dashboardMapMarker: rem(10),
  dashboardMapTool: rem(18),
  dashboardMapLegend: rem(10),
  dashboardAlarmSummary: rem(10),
  dashboardAlarmTitle: rem(11),
  dashboardAlarmMeta: rem(10),
  dashboardAlarmBadge: rem(10),
  dashboardAlarmTime: rem(10),
  dashboardPageButton: rem(10),
  dashboardFilter: rem(10),
  dashboardChartLegend: rem(10),
  dashboardAxis: rem(10),
  dashboardHeatmapLabel: rem(10),
  dashboardCheckMark: "8px",
};
