import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Download, Eye, RefreshCw, RotateCcw, Search, X } from "lucide-react";
import styled from "styled-components";
import { useAuth } from "../auth/authStore";
import { API_BASE_URL, apiFetch, readApiError } from "../config/api";
import { BUSINESS_PAGE_LAYOUT, COLORS, FONT_SIZES } from "../constants/STYLES";

function LogDetail({ log, onClose }) {
  if (!log) return null;
  const changes = typeof log.changes === "string" ? JSON.parse(log.changes || "{}") : log.changes || {};
  return <Backdrop onMouseDown={onClose}><DetailPanel onMouseDown={(event) => event.stopPropagation()}><DetailHeader><div><h2>操作日志详情</h2><p>{log.id}</p></div><IconButton type="button" title="关闭" onClick={onClose}><X size={17} /></IconButton></DetailHeader><DetailBody><Section><h3>操作信息</h3><DetailGrid><Info><span>操作时间</span><strong>{new Date(log.created_at).toLocaleString("zh-CN", { hour12: false })}</strong></Info><Info><span>操作用户</span><strong>{log.display_name || "未知用户"} / {log.username || "--"}</strong></Info><Info><span>业务模块</span><strong>{log.module}</strong></Info><Info><span>操作类型</span><strong>{log.action}</strong></Info><Info><span>操作对象</span><strong>{log.target_id || "--"}</strong></Info><Info><span>执行结果</span><Result $success={log.result === "success"}>{log.result === "success" ? "成功" : "失败"}</Result></Info></DetailGrid></Section><Section><h3>请求信息</h3><DetailGrid><Info><span>来源IP</span><Code>{log.ip_address || "--"}</Code></Info><Info><span>对象类型</span><Code>{log.target_type || "--"}</Code></Info></DetailGrid></Section><Section><h3>操作说明</h3><Description>{log.detail || "无补充说明"}</Description>{Object.keys(changes).length ? <ChangeBox><span>结构化变更</span><pre>{JSON.stringify(changes, null, 2)}</pre></ChangeBox> : null}</Section></DetailBody></DetailPanel></Backdrop>;
}

function OperationLogs() {
  const { hasPermission } = useAuth();
  const [logs, setLogs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [selectedLog, setSelectedLog] = useState(null);
  const [filters, setFilters] = useState({ keyword: "", module: "all", result: "all", date: "" });
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams(); if (filters.keyword.trim()) params.set("keyword", filters.keyword.trim()); if (filters.module !== "all") params.set("module", filters.module); if (filters.result !== "all") params.set("result", filters.result); if (filters.date) params.set("date", filters.date); const response = await apiFetch(`${API_BASE_URL}/system/operation-logs?${params}`); if (!response.ok) throw new Error(await readApiError(response)); const payload = await response.json(); setLogs(payload.items || []); } catch (nextError) { setError(nextError.message); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = window.setTimeout(load, 200); return () => window.clearTimeout(timer); }, [load]);
  const modules = useMemo(() => [...new Set(logs.map((log) => log.module))], [logs]);
  function update(key) { return (event) => setFilters((current) => ({ ...current, [key]: event.target.value })); }
  function exportLogs() { const header = ["日志编号","操作时间","用户","账号","模块","操作","对象","结果","IP"]; const rows = logs.map((log) => [log.id,log.created_at,log.display_name,log.username,log.module,log.action,log.target_id,log.result,log.ip_address]); const csv = `\uFEFF${[header,...rows].map((row) => row.map((value) => `"${String(value ?? "").replaceAll('"','""')}"`).join(",")).join("\n")}`; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "petroshield-operation-logs.csv"; anchor.click(); URL.revokeObjectURL(url); }
  return <Page><PageHeader><div><PageTitle>操作日志</PageTitle><PageSubtitle>审计真实登录、用户管理与角色授权操作</PageSubtitle></div><HeaderActions>{hasPermission("system.logs.export") ? <SecondaryButton type="button" onClick={exportLogs}><Download size={15} />导出</SecondaryButton> : null}<IconButton type="button" title="刷新日志" onClick={load}><RefreshCw size={15} /></IconButton></HeaderActions></PageHeader><SummaryBand><Summary><span>当前记录</span><strong>{logs.length}</strong></Summary><Summary><span>成功操作</span><strong>{logs.filter((log) => log.result === "success").length}</strong></Summary><Summary><span>失败操作</span><strong>{logs.filter((log) => log.result === "failure").length}</strong></Summary><Summary><span>活跃用户</span><strong>{new Set(logs.map((log) => log.username).filter(Boolean)).size}</strong></Summary></SummaryBand><Toolbar><SearchBox><Search size={15} /><input value={filters.keyword} onChange={update("keyword")} placeholder="搜索用户、对象、操作或日志编号" /></SearchBox><Select value={filters.module} onChange={update("module")}><option value="all">全部模块</option>{modules.map((module) => <option key={module}>{module}</option>)}</Select><Select value={filters.result} onChange={update("result")}><option value="all">全部结果</option><option value="success">成功</option><option value="failure">失败</option></Select><DateInput type="date" value={filters.date} onChange={update("date")} /><SecondaryButton type="button" onClick={() => setFilters({ keyword: "", module: "all", result: "all", date: "" })}><RotateCcw size={14} />重置</SecondaryButton></Toolbar><TablePanel><Table><thead><tr><th>操作时间</th><th>操作用户</th><th>业务模块</th><th>操作类型</th><th>操作对象</th><th>结果</th><th>来源IP</th><th>详情</th></tr></thead><tbody>{loading || error ? <tr><EmptyCell colSpan="8">{loading ? "正在加载操作日志..." : error}</EmptyCell></tr> : logs.map((log) => <tr key={log.id}><td>{new Date(log.created_at).toLocaleString("zh-CN", { hour12: false })}</td><td><UserCell><strong>{log.display_name || "未知用户"}</strong><span>{log.username || "--"}</span></UserCell></td><td>{log.module}</td><td>{log.action}</td><td>{log.target_id || "--"}</td><td><Result $success={log.result === "success"}>{log.result === "success" ? "成功" : "失败"}</Result></td><td><Code>{log.ip_address || "--"}</Code></td><td><IconButton type="button" title="查看日志详情" onClick={() => setSelectedLog(log)}><Eye size={15} /></IconButton></td></tr>)}{!loading && !error && !logs.length ? <tr><EmptyCell colSpan="8">暂无符合条件的操作日志</EmptyCell></tr> : null}</tbody></Table></TablePanel><Footer><span>共 {logs.length} 条记录</span><span>系统认证与权限变更由后端自动审计</span></Footer><LogDetail log={selectedLog} onClose={() => setSelectedLog(null)} /></Page>;
}

const Page = styled.div`height:100%;min-height:0;display:grid;grid-template-rows:auto 62px auto minmax(0,1fr) auto;gap:10px;padding:${BUSINESS_PAGE_LAYOUT.padding};overflow:hidden;background:hsl(216 26% 97%);color:hsl(218 22% 22%);`;
const PageHeader = styled.header`display:flex;align-items:center;justify-content:space-between;gap:16px;`;
const PageTitle = styled.h1`margin:0;color:${COLORS.gray10};font-size:${FONT_SIZES.peoplePageTitle};line-height:${BUSINESS_PAGE_LAYOUT.titleLineHeight};`;
const PageSubtitle = styled.p`margin-top:4px;color:hsl(218 10% 48%);font-size:11px;`;
const HeaderActions = styled.div`display:flex;gap:7px;`;
const SummaryBand = styled.section`display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid hsl(218 18% 88%);border-radius:6px;background:white;overflow:hidden;`;
const Summary = styled.div`display:flex;align-items:center;justify-content:space-between;padding:0 18px;border-right:1px solid hsl(218 18% 90%);color:hsl(218 10% 46%);font-size:12px;&:last-child{border:0}strong{font-size:20px;color:hsl(218 25% 18%)}`;
const control = `height:34px;border:1px solid hsl(220 13% 84%);border-radius:6px;background:white;color:hsl(218 18% 25%);font-size:12px;outline:none;&:focus{border-color:hsl(220 88% 58%);box-shadow:0 0 0 2px hsl(220 90% 94%);}`;
const Toolbar = styled.div`display:grid;grid-template-columns:minmax(260px,1fr) 150px 120px 150px auto;gap:8px;align-items:center;`;
const SearchBox = styled.label`${control} display:flex;align-items:center;gap:8px;padding:0 10px;color:hsl(218 10% 52%);input{min-width:0;flex:1;border:0;outline:0;background:transparent;font-size:12px}`;
const Select = styled.select`${control} padding:0 10px;`;
const DateInput = styled.input`${control} padding:0 9px;`;
const SecondaryButton = styled.button`height:34px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:0 13px;border:1px solid hsl(218 18% 84%);border-radius:6px;background:white;color:hsl(218 16% 30%);font-size:12px;cursor:pointer;`;
const IconButton = styled.button`width:30px;height:30px;display:grid;place-items:center;border:1px solid hsl(218 18% 86%);border-radius:5px;color:hsl(218 14% 42%);background:white;cursor:pointer;&:hover{color:${COLORS.blue}}`;
const TablePanel = styled.section`min-height:0;overflow:auto;border:1px solid hsl(218 18% 88%);border-radius:6px;background:white;`;
const Table = styled.table`width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px;th{position:sticky;top:0;z-index:1;height:38px;padding:0 12px;text-align:left;background:hsl(216 28% 97%);color:hsl(218 12% 42%);font-weight:600;border-bottom:1px solid hsl(218 18% 88%)}td{height:51px;padding:0 12px;border-bottom:1px solid hsl(218 18% 92%);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}th:nth-child(1){width:17%}th:nth-child(2){width:13%}th:nth-child(3){width:13%}th:nth-child(4){width:12%}th:nth-child(5){width:18%}th:nth-child(6){width:8%}th:nth-child(7){width:11%}th:nth-child(8){width:8%}`;
const UserCell = styled.span`display:grid;gap:2px;span{color:hsl(218 10% 52%);font-size:9px}`;
const Result = styled.strong`display:inline-flex;padding:3px 8px;border-radius:4px;color:${(p) => p.$success ? "hsl(157 64% 34%)" : "hsl(2 70% 48%)"};background:${(p) => p.$success ? "hsl(157 55% 94%)" : "hsl(2 78% 96%)"};font-size:10px;`;
const Code = styled.code`font-family:var(--font-data);font-size:10px;`;
const EmptyCell = styled.td`height:180px!important;text-align:center;color:hsl(218 10% 52%);`;
const Footer = styled.footer`display:flex;justify-content:space-between;color:hsl(218 10% 50%);font-size:10px;`;
const Backdrop = styled.div`position:fixed;inset:0;z-index:1000;display:flex;justify-content:flex-end;background:rgba(15,23,42,.38);`;
const DetailPanel = styled.section`width:500px;height:100%;display:grid;grid-template-rows:auto minmax(0,1fr);background:white;box-shadow:-12px 0 36px rgba(15,23,42,.16);`;
const DetailHeader = styled.header`display:flex;justify-content:space-between;padding:18px 20px;border-bottom:1px solid hsl(218 18% 90%);h2{font-size:16px}p{margin-top:4px;font-family:var(--font-data);font-size:10px;color:hsl(218 10% 48%)}`;
const DetailBody = styled.div`min-height:0;overflow:auto;padding:18px 20px;`;
const Section = styled.section`margin-bottom:22px;h3{margin-bottom:12px;font-size:13px}`;
const DetailGrid = styled.div`display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;`;
const Info = styled.div`display:grid;gap:5px;span{color:hsl(218 10% 50%);font-size:10px}strong{font-size:12px;font-weight:500}`;
const Description = styled.p`padding:11px 12px;border-radius:5px;background:hsl(216 28% 97%);font-size:11px;line-height:1.6;`;
const ChangeBox = styled.div`margin-top:10px;padding:11px;border-left:3px solid hsl(220 72% 52%);background:hsl(220 70% 98%);span{font-size:10px;color:hsl(218 10% 50%)}pre{margin-top:6px;white-space:pre-wrap;font-family:var(--font-data);font-size:10px;line-height:1.5}`;
export default OperationLogs;
