import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, Plus, RefreshCw, Save, ShieldCheck, Users, X } from "lucide-react";
import styled from "styled-components";
import { useAuth } from "../auth/authStore";
import { API_BASE_URL, apiFetch, readApiError } from "../config/api";
import { BUSINESS_PAGE_LAYOUT, COLORS, FONT_SIZES } from "../constants/STYLES";

const MODULE_LABELS = { dashboard: ["首页", "综合态势首页"], people: ["人员管理", "人员位置、轨迹与档案"], alarms: ["告警中心", "告警确认、派发与关闭"], devices: ["设备管理", "设备台账及运行状态"], risk: ["风险管控", "电子围栏及区域规则"], video: ["视频AI", "视频智能分析"], statistics: ["统计分析", "态势、事件与报表"], system_users: ["用户管理", "登录账号与状态"], system_roles: ["角色权限", "角色与授权范围"], system_dictionaries: ["数据字典", "业务编码和枚举"], system_logs: ["操作日志", "系统审计记录"], system_api: ["API配置", "外部服务连接"] };

function NewRoleDialog({ onClose, onSubmit, busy }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState("");
  return <Backdrop onMouseDown={onClose}><Dialog onMouseDown={(event) => event.stopPropagation()}><DialogHeader><div><h2>新增角色</h2><p>创建后可立即配置功能权限</p></div><IconButton type="button" title="关闭" onClick={onClose}><X size={17} /></IconButton></DialogHeader><DialogBody><Field><span>角色名称</span><input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="请输入角色名称" /></Field><Field><span>角色说明</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="说明该角色的职责范围" /></Field><DialogActions><SecondaryButton type="button" onClick={onClose}>取消</SecondaryButton><PrimaryButton type="button" disabled={busy || !name.trim()} onClick={() => onSubmit(name.trim(), description.trim())}>{busy ? "创建中..." : "创建角色"}</PrimaryButton></DialogActions></DialogBody></Dialog></Backdrop>;
}

function RolePermission() {
  const { hasPermission } = useAuth();
  const [roles, setRoles] = useState([]); const [permissions, setPermissions] = useState([]); const [selectedId, setSelectedId] = useState(null); const [draftCodes, setDraftCodes] = useState([]); const [savedCodes, setSavedCodes] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showNewRole, setShowNewRole] = useState(false); const [notice, setNotice] = useState("");
  const selectedRole = roles.find((role) => role.id === selectedId) || roles[0];
  const groups = useMemo(() => Object.entries(permissions.reduce((result, permission) => { (result[permission.module] ||= []).push(permission); return result; }, {})), [permissions]);
  const dirty = JSON.stringify([...draftCodes].sort()) !== JSON.stringify([...savedCodes].sort());
  const load = useCallback(async (preferredId) => { setLoading(true); setError(""); try { const [rolesResponse, permissionsResponse] = await Promise.all([apiFetch(`${API_BASE_URL}/system/roles`), apiFetch(`${API_BASE_URL}/system/permissions`)]); if (!rolesResponse.ok) throw new Error(await readApiError(rolesResponse)); if (!permissionsResponse.ok) throw new Error(await readApiError(permissionsResponse)); const [rolesPayload, permissionsPayload] = await Promise.all([rolesResponse.json(), permissionsResponse.json()]); const nextRoles = rolesPayload.items || []; setRoles(nextRoles); setPermissions(permissionsPayload.items || []); const nextRole = nextRoles.find((role) => role.id === preferredId) || nextRoles[0]; setSelectedId(nextRole?.id || null); setDraftCodes(nextRole?.permission_codes || []); setSavedCodes(nextRole?.permission_codes || []); } catch (nextError) { setError(nextError.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  function selectRole(role) { if (dirty && !window.confirm("当前权限尚未保存，确定切换角色吗？")) return; setSelectedId(role.id); setDraftCodes(role.permission_codes || []); setSavedCodes(role.permission_codes || []); }
  function toggle(code) { setDraftCodes((current) => current.includes(code) ? current.filter((item) => item !== code) : [...current, code]); }
  function toggleModule(modulePermissions) { const codes = modulePermissions.map((permission) => permission.code); const all = codes.every((code) => draftCodes.includes(code)); setDraftCodes((current) => all ? current.filter((code) => !codes.includes(code)) : [...new Set([...current, ...codes])]); }
  function notify(message) { setNotice(message); window.setTimeout(() => setNotice(""), 2200); }
  async function save() { setBusy(true); try { const response = await apiFetch(`${API_BASE_URL}/system/roles/${selectedRole.id}/permissions`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ permission_codes: draftCodes }) }); if (!response.ok) throw new Error(await readApiError(response)); notify("角色权限已保存并立即生效"); await load(selectedRole.id); } catch (nextError) { notify(nextError.message); } finally { setBusy(false); } }
  async function createRole(name, description) { setBusy(true); try { const response = await apiFetch(`${API_BASE_URL}/system/roles`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description: description || null }) }); if (!response.ok) throw new Error(await readApiError(response)); const payload = await response.json(); setShowNewRole(false); notify("角色已创建"); await load(payload.id); } catch (nextError) { notify(nextError.message); } finally { setBusy(false); } }
  const editable = hasPermission("system.roles.edit") && selectedRole?.name !== "超级管理员";
  return <Page><PageHeader><div><PageTitle>角色权限</PageTitle><PageSubtitle>角色权限由后端强制校验，保存后立即影响所属用户</PageSubtitle></div><HeaderActions><IconButton type="button" title="刷新角色" onClick={() => load(selectedId)}><RefreshCw size={15} /></IconButton>{hasPermission("system.roles.edit") ? <PrimaryButton type="button" onClick={() => setShowNewRole(true)}><Plus size={15} />新增角色</PrimaryButton> : null}</HeaderActions></PageHeader><Workspace><RoleSidebar><PanelHeading><div><strong>角色列表</strong><span>{roles.length} 个角色</span></div></PanelHeading><RoleList>{roles.map((role) => <RoleButton key={role.id} type="button" $active={role.id === selectedRole?.id} onClick={() => selectRole(role)}><RoleIcon><ShieldCheck size={16} /></RoleIcon><RoleText><strong>{role.name}</strong><span><Users size={12} />{role.user_count} 名用户{role.is_system ? " · 内置" : ""}</span></RoleText><ChevronRight size={15} /></RoleButton>)}{loading || error ? <SideMessage>{loading ? "正在加载角色..." : error}</SideMessage> : null}</RoleList></RoleSidebar><PermissionPanel><PermissionHeader><div><h2>{selectedRole?.name || "角色权限"}</h2><p>{selectedRole?.description || "请选择角色"}</p></div><PermissionMeta><span>{draftCodes.length} 项权限</span>{dirty ? <Changed>未保存</Changed> : <Saved><Check size={13} />已保存</Saved>}</PermissionMeta></PermissionHeader><MatrixHeader><span>功能模块</span><span>权限配置</span><span>模块全选</span></MatrixHeader><MatrixBody>{groups.map(([module, modulePermissions]) => { const label = MODULE_LABELS[module] || [module,module]; const all = modulePermissions.every((permission) => draftCodes.includes(permission.code)); return <PermissionRow key={module}><ModuleInfo><strong>{label[0]}</strong><span>{label[1]}</span></ModuleInfo><Actions>{modulePermissions.map((permission) => <CheckLabel key={permission.code} $disabled={!editable}><input type="checkbox" disabled={!editable} checked={draftCodes.includes(permission.code)} onChange={() => toggle(permission.code)} /><i><Check size={11} /></i><span>{permission.name.replace(label[0], "") || permission.action}</span></CheckLabel>)}</Actions><CheckLabel $disabled={!editable}><input type="checkbox" disabled={!editable} checked={all} onChange={() => toggleModule(modulePermissions)} /><i><Check size={11} /></i><span>全部</span></CheckLabel></PermissionRow>; })}</MatrixBody><PermissionFooter><span>{selectedRole?.name === "超级管理员" ? "超级管理员固定拥有全部权限，不允许削减" : "后端接口与前端路由会同时应用权限结果"}</span><PrimaryButton type="button" disabled={!editable || !dirty || busy} onClick={save}><Save size={15} />{busy ? "保存中..." : "保存权限"}</PrimaryButton></PermissionFooter></PermissionPanel></Workspace>{showNewRole ? <NewRoleDialog onClose={() => setShowNewRole(false)} onSubmit={createRole} busy={busy} /> : null}{notice ? <Toast>{notice}</Toast> : null}</Page>;
}

const Page = styled.div`height:100%;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr);gap:10px;padding:${BUSINESS_PAGE_LAYOUT.padding};overflow:hidden;background:hsl(216 26% 97%);color:hsl(218 22% 22%);`;
const PageHeader = styled.header`display:flex;align-items:center;justify-content:space-between;gap:16px;`;
const PageTitle = styled.h1`margin:0;color:${COLORS.gray10};font-size:${FONT_SIZES.peoplePageTitle};line-height:${BUSINESS_PAGE_LAYOUT.titleLineHeight};`;
const PageSubtitle = styled.p`margin-top:4px;color:hsl(218 10% 48%);font-size:11px;`;
const HeaderActions = styled.div`display:flex;gap:7px;`;
const Workspace = styled.div`min-height:0;display:grid;grid-template-columns:260px minmax(0,1fr);gap:10px;`;
const RoleSidebar = styled.aside`min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr);border:1px solid hsl(218 18% 88%);border-radius:6px;background:white;overflow:hidden;`;
const PanelHeading = styled.header`height:54px;display:flex;align-items:center;padding:0 14px;border-bottom:1px solid hsl(218 18% 90%);strong{display:block;font-size:13px}span{display:block;margin-top:3px;color:hsl(218 10% 50%);font-size:10px}`;
const RoleList = styled.div`min-height:0;overflow:auto;padding:7px;`;
const RoleButton = styled.button`width:100%;min-height:60px;display:grid;grid-template-columns:30px minmax(0,1fr) 15px;align-items:center;gap:9px;margin-bottom:4px;padding:8px;border:0;border-radius:5px;text-align:left;color:${(p) => p.$active ? "hsl(220 84% 45%)" : "hsl(218 18% 28%)"};background:${(p) => p.$active ? "hsl(220 90% 95%)" : "transparent"};cursor:pointer;&:hover{background:hsl(216 34% 96%)}svg:last-child{color:hsl(218 12% 64%)}`;
const RoleIcon = styled.span`width:30px;height:30px;display:grid;place-items:center;border-radius:5px;color:currentColor;background:white;border:1px solid hsl(218 18% 88%);`;
const RoleText = styled.span`min-width:0;strong{display:block;font-size:12px}span{display:flex;align-items:center;gap:4px;margin-top:5px;color:hsl(218 10% 50%);font-size:10px}`;
const SideMessage = styled.p`padding:14px;color:hsl(218 10% 50%);font-size:10px;text-align:center;`;
const PermissionPanel = styled.section`min-width:0;min-height:0;display:grid;grid-template-rows:auto 38px minmax(0,1fr) auto;border:1px solid hsl(218 18% 88%);border-radius:6px;background:white;overflow:hidden;`;
const PermissionHeader = styled.header`height:64px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 16px;border-bottom:1px solid hsl(218 18% 90%);h2{margin:0;font-size:15px}p{margin-top:4px;color:hsl(218 10% 48%);font-size:11px}`;
const PermissionMeta = styled.div`display:flex;align-items:center;gap:8px;color:hsl(218 10% 48%);font-size:11px;`;
const Changed = styled.span`padding:3px 7px;border-radius:4px;color:hsl(35 80% 38%);background:hsl(38 90% 94%);`;
const Saved = styled.span`display:inline-flex;align-items:center;gap:3px;padding:3px 7px;border-radius:4px;color:hsl(157 64% 34%);background:hsl(157 55% 94%);`;
const MatrixHeader = styled.div`display:grid;grid-template-columns:220px minmax(0,1fr) 90px;align-items:center;padding:0 16px;color:hsl(218 11% 45%);background:hsl(216 28% 97%);font-size:11px;font-weight:600;`;
const MatrixBody = styled.div`min-height:0;overflow:auto;`;
const PermissionRow = styled.div`min-height:62px;display:grid;grid-template-columns:220px minmax(0,1fr) 90px;align-items:center;padding:8px 16px;border-bottom:1px solid hsl(218 18% 92%);&:hover{background:hsl(216 55% 98%)}`;
const ModuleInfo = styled.div`min-width:0;strong{display:block;font-size:12px}span{display:block;margin-top:4px;color:hsl(218 10% 50%);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}`;
const Actions = styled.div`display:flex;align-items:center;gap:16px;flex-wrap:wrap;`;
const CheckLabel = styled.label`display:inline-flex;align-items:center;gap:6px;color:${(p) => p.$disabled ? "hsl(218 9% 54%)" : "hsl(218 16% 34%)"};font-size:11px;cursor:${(p) => p.$disabled ? "not-allowed" : "pointer"};input{position:absolute;opacity:0;pointer-events:none}i{width:16px;height:16px;display:grid;place-items:center;border:1px solid hsl(218 16% 76%);border-radius:3px;color:transparent;background:white}input:checked+i{border-color:${COLORS.blue};color:white;background:${COLORS.blue}}`;
const PermissionFooter = styled.footer`height:54px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 16px;border-top:1px solid hsl(218 18% 90%);color:hsl(218 10% 50%);font-size:10px;`;
const PrimaryButton = styled.button`height:34px;display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:0 14px;border:0;border-radius:6px;color:white;background:${COLORS.blue};font-size:12px;cursor:pointer;&:disabled{cursor:not-allowed;background:hsl(218 15% 72%)}`;
const SecondaryButton = styled.button`height:34px;padding:0 16px;border:1px solid hsl(218 18% 84%);border-radius:6px;background:white;color:hsl(218 16% 30%);font-size:12px;cursor:pointer;`;
const IconButton = styled.button`width:30px;height:30px;display:grid;place-items:center;border:1px solid hsl(218 18% 86%);border-radius:5px;color:hsl(218 14% 42%);background:white;cursor:pointer;`;
const Backdrop = styled.div`position:fixed;inset:0;z-index:1000;display:grid;place-items:center;background:rgba(15,23,42,.42);`;
const Dialog = styled.section`width:480px;border-radius:7px;background:white;box-shadow:0 18px 46px rgba(15,23,42,.22);overflow:hidden;`;
const DialogHeader = styled.header`display:flex;align-items:flex-start;justify-content:space-between;padding:18px 20px;border-bottom:1px solid hsl(218 18% 90%);h2{font-size:16px;margin:0}p{margin-top:4px;color:hsl(218 10% 48%);font-size:11px}`;
const DialogBody = styled.div`display:grid;gap:14px;padding:18px 20px;`;
const Field = styled.label`display:grid;gap:6px;color:hsl(218 14% 34%);font-size:12px;input,textarea{width:100%;border:1px solid hsl(220 13% 84%);border-radius:6px;padding:9px 10px;outline:none;font-size:12px}textarea{height:76px;resize:none}`;
const DialogActions = styled.footer`display:flex;justify-content:flex-end;gap:8px;margin-top:4px;`;
const Toast = styled.div`position:fixed;right:24px;top:76px;z-index:1100;padding:10px 15px;border-radius:6px;color:white;background:hsl(218 28% 22%);box-shadow:0 8px 24px rgba(15,23,42,.18);font-size:12px;`;
export default RolePermission;
